http_port: "8000"
DB:
  HOST: "localhost"
  PORT: "32768"
  USER: "postgres"
  PASSWORD: "pass"
  DBNAME: "test_db"

  DRIVER: "postgres"
  URLTEMPLATE: "host=%s port=%s dbname=%s user=%s password=%s sslmode=disable"

AMQP:
  HOST: "localhost"
  PORT: "5672"
  USER: "guest"
  PASSWORD: "guest"

  DRIVER: "amqp"
  URLTEMPLATE: "://%s:%s@%s:%s/"